"""
Report generation: turn a `SolutionBlueprint` into a downloadable PDF and a
Markdown string.

PDF uses fpdf2 with the built-in Helvetica core font, so it needs no external
font files. Text is sanitised to latin-1 (the core-font charset) so unusual
unicode never crashes the export.
"""
from __future__ import annotations

import io

from utils.schemas import SolutionBlueprint


# ── Markdown ──────────────────────────────────────────────────────────────
def build_markdown(bp: SolutionBlueprint) -> str:
    r, a, e, k, p = bp.requirement, bp.architecture, bp.estimation, bp.risk, bp.proposal
    ts = a.tech_stack
    L = []
    L.append(f"# Solution Blueprint — {r.project_name}\n")
    mode = "GPT-4o" if bp.generated_with_llm else "Demo mode (no API key)"
    L.append(f"_Generated by the AI Solution Architect Agent · {mode}_\n")

    L.append("## 1. Requirement Analysis")
    L.append(f"**Business Goal:** {r.business_goal}\n")
    L.append(f"**Target Users:** {', '.join(r.target_users)}\n")
    L.append("**Key Features:**")
    L += [f"- {f}" for f in r.key_features]
    L.append("\n**Integrations:**")
    L += [f"- {i}" for i in r.integrations]
    L.append("\n**Constraints:**")
    L += [f"- {c}" for c in r.constraints]
    L.append(f"\n**Summary:** {r.summary}\n")

    L.append("## 2. Architecture Recommendation")
    L.append(f"{a.overview}\n")
    L.append("**Components:**")
    L += [f"- {c}" for c in a.components]
    L.append(f"\n**Data Flow:** {a.data_flow}\n")
    L.append("```mermaid")
    L.append(a.mermaid_diagram)
    L.append("```\n")

    L.append("## 3. Recommended Tech Stack")
    for label, val in [
        ("Frontend", ts.frontend), ("Backend", ts.backend), ("LLM", ts.llm),
        ("AI Framework", ts.ai_framework), ("Vector Database", ts.vector_database),
        ("Database", ts.database), ("Deployment", ts.deployment),
    ]:
        if val:
            L.append(f"- **{label}:** {val}")
    if ts.other:
        L.append(f"- **Other:** {', '.join(ts.other)}")

    L.append("\n## 4. Effort Estimation")
    L.append("| Phase | Effort (days) |")
    L.append("|---|---|")
    for item in e.breakdown:
        L.append(f"| {item.phase} | {item.days:g} |")
    L.append(f"| **Total** | **{e.total_days:g}** |")
    L.append("\n**Team:**")
    L += [f"- {m.count} × {m.role}" for m in e.team]
    if e.assumptions:
        L.append("\n**Assumptions:**")
        L += [f"- {x}" for x in e.assumptions]

    L.append("\n## 5. Risk Analysis")
    L.append("| Risk | Impact | Likelihood | Mitigation |")
    L.append("|---|---|---|---|")
    for ri in k.risks:
        L.append(f"| {ri.risk} | {ri.impact} | {ri.likelihood} | {ri.mitigation} |")

    L.append("\n## 6. Proposal Summary")
    L.append(f"**Executive Summary:** {p.executive_summary}\n")
    L.append(f"**Recommended Solution:** {p.recommended_solution}\n")
    L.append(f"**Timeline:** {p.timeline}\n")
    L.append(f"**Team Structure:** {p.team_structure}\n")
    if p.assumptions:
        L.append("**Assumptions:**")
        L += [f"- {x}" for x in p.assumptions]
    if p.risks:
        L.append("\n**Key Risks:**")
        L += [f"- {x}" for x in p.risks]
    if p.next_steps:
        L.append("\n**Next Steps:**")
        L += [f"- {x}" for x in p.next_steps]

    return "\n".join(L)


# ── PDF ───────────────────────────────────────────────────────────────────
def _s(text: str) -> str:
    """Sanitise to the latin-1 charset used by fpdf2 core fonts."""
    if text is None:
        return ""
    replacements = {
        "‘": "'", "’": "'", "“": '"', "”": '"',
        "–": "-", "—": "-", "…": "...", "×": "x",
        "→": "->", "•": "-", " ": " ",
    }
    for bad, good in replacements.items():
        text = text.replace(bad, good)
    return text.encode("latin-1", "replace").decode("latin-1")


class _PDF:
    """Thin wrapper around fpdf2 with consulting-report styling helpers."""

    BRAND = (37, 99, 235)  # blue

    def __init__(self):
        from fpdf import FPDF

        self.pdf = FPDF()
        self.pdf.set_auto_page_break(auto=True, margin=18)
        self.pdf.add_page()
        self.pdf.set_title("Solution Blueprint")

    def _reset_x(self):
        """Pin the cursor to the left margin so multi_cell always has full width.

        write() can leave x mid-line; a following multi_cell(0,...) would then
        compute a near-zero width and fpdf2 raises 'Not enough horizontal space'.
        """
        self.pdf.set_x(self.pdf.l_margin)

    def h1(self, text):
        self._reset_x()
        self.pdf.set_font("Helvetica", "B", 18)
        self.pdf.set_text_color(*self.BRAND)
        self.pdf.multi_cell(0, 9, _s(text))
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.ln(2)

    def h2(self, text):
        self._reset_x()
        self.pdf.ln(3)
        self.pdf.set_font("Helvetica", "B", 13)
        self.pdf.set_text_color(*self.BRAND)
        self.pdf.multi_cell(0, 7, _s(text))
        self.pdf.set_text_color(0, 0, 0)
        self.pdf.ln(1)

    def label(self, label, value):
        # write() flows text inline and wraps at the right margin, which avoids
        # the width-exhaustion pitfalls of mixing cell() + multi_cell().
        self._reset_x()
        self.pdf.set_font("Helvetica", "B", 10)
        self.pdf.write(6, _s(label))
        self.pdf.set_font("Helvetica", "", 10)
        self.pdf.write(6, _s(value))
        self.pdf.ln(8)

    def body(self, text):
        self._reset_x()
        self.pdf.set_font("Helvetica", "", 10)
        self.pdf.multi_cell(0, 6, _s(text))

    def bullets(self, items):
        self.pdf.set_font("Helvetica", "", 10)
        for it in items:
            self._reset_x()
            self.pdf.multi_cell(0, 6, _s(f"  - {it}"))

    def kv_table(self, rows):
        self.pdf.set_font("Helvetica", "", 10)
        for k, v in rows:
            self._reset_x()
            self.pdf.set_font("Helvetica", "B", 10)
            self.pdf.cell(45, 7, _s(k), border=1)
            self.pdf.set_font("Helvetica", "", 10)
            self.pdf.multi_cell(0, 7, _s(v), border=1)

    def out(self) -> bytes:
        raw = self.pdf.output()
        return bytes(raw)


def build_pdf(bp: SolutionBlueprint) -> bytes:
    r, a, e, k, p = bp.requirement, bp.architecture, bp.estimation, bp.risk, bp.proposal
    ts = a.tech_stack
    doc = _PDF()

    doc.h1(f"Solution Blueprint: {r.project_name}")
    mode = "Generated with GPT-4o" if bp.generated_with_llm else "Generated in demo mode"
    doc.body(f"AI Solution Architect Agent  -  {mode}")

    # 1. Requirement
    doc.h2("1. Requirement Analysis")
    doc.label("Business Goal: ", r.business_goal)
    doc.label("Target Users: ", ", ".join(r.target_users))
    doc.body("Key Features:")
    doc.bullets(r.key_features)
    doc.body("Integrations:")
    doc.bullets(r.integrations)
    doc.body("Constraints:")
    doc.bullets(r.constraints)

    # 2. Architecture
    doc.h2("2. Architecture Recommendation")
    doc.body(a.overview)
    doc.body("Components:")
    doc.bullets(a.components)
    doc.label("Data Flow: ", a.data_flow)

    # 3. Tech stack
    doc.h2("3. Recommended Tech Stack")
    rows = [
        ("Frontend", ts.frontend), ("Backend", ts.backend), ("LLM", ts.llm),
        ("AI Framework", ts.ai_framework), ("Vector DB", ts.vector_database),
        ("Database", ts.database), ("Deployment", ts.deployment),
    ]
    if ts.other:
        rows.append(("Other", ", ".join(ts.other)))
    doc.kv_table([(kk, vv) for kk, vv in rows if vv])

    # 4. Effort
    doc.h2("4. Effort Estimation")
    doc.kv_table([(item.phase, f"{item.days:g} days") for item in e.breakdown]
                 + [("TOTAL", f"{e.total_days:g} days")])
    doc.body("Team:")
    doc.bullets([f"{m.count} x {m.role}" for m in e.team])

    # 5. Risks
    doc.h2("5. Risk Analysis")
    for ri in k.risks:
        doc.label(f"{ri.risk} ", f"[{ri.impact} impact / {ri.likelihood} likelihood]")
        doc.body(f"   Mitigation: {ri.mitigation}")

    # 6. Proposal
    doc.h2("6. Proposal Summary")
    doc.label("Executive Summary: ", p.executive_summary)
    doc.label("Recommended Solution: ", p.recommended_solution)
    doc.label("Timeline: ", p.timeline)
    doc.label("Team Structure: ", p.team_structure)
    if p.assumptions:
        doc.body("Assumptions:")
        doc.bullets(p.assumptions)
    if p.next_steps:
        doc.body("Next Steps:")
        doc.bullets(p.next_steps)

    return doc.out()
